# Generated by Django 5.2.15 on 2026-06-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('trainee', 'Стажёр'), ('inactive', 'Неактивен')], default='active', max_length=16)),
                ('hired_at', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['status'], name='operators_o_status_02c2c4_idx')],
            },
        ),
    ]
