# Generated by Django 5.2.15 on 2026-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operatormonthlyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='daily_lesson_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
