# Generated by Django 5.2.16 on 2026-07-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_operator_daily_lesson_opt_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='personal_phone',
            field=models.CharField(blank=True, default='', help_text='Личный номер оператора. Опционально.', max_length=32),
        ),
        migrations.AlterField(
            model_name='operator',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Рабочий номер (+998XXXXXXXXX). Используется для входа и Telegram.', max_length=32),
        ),
    ]
