# Generated by Django 5.2.15 on 2026-08-31 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_operator_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='grace_period_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Персональный grace для опозданий (мин). Пусто → default_grace_period_min.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='operator',
            name='late_penalty_uzs',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Персональный фикс. штраф за опоздание (UZS). Пусто → default_late_penalty_uzs.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='salary_uzs',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Оклад оператора в UZS. Пусто → default_salary_uzs из настроек.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='shift_end',
            field=models.TimeField(blank=True, help_text='Персональный конец смены. Пусто → shift_end из настроек.', null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='shift_start',
            field=models.TimeField(blank=True, help_text='Персональное начало смены. Пусто → shift_start из настроек.', null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='weekly_day_off',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Персональный выходной день (0=Пн … 6=Вс). Пусто → default_weekly_day_off.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='operator',
            name='weekly_free_absences',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Персональный лимит «прощённых» пропусков в неделю. Пусто → default_weekly_free_absences.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
