# Generated by Django 5.2.15 on 2026-07-24 09:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0003_operator_daily_lesson_opt_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(db_index=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('checked_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('checked_in_user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('checked_out_user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('auto_closed', models.BooleanField(default=False)),
                ('was_late', models.BooleanField(default=False, help_text='Set at check-in time: True if checked_in_at > shift_start + late_threshold_min')),
                ('token_key', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('qr', 'qr'), ('tg', 'tg'), ('manual', 'manual')], default='qr', help_text='Channel used to record the event', max_length=16)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='operators.operator')),
            ],
            options={
                'indexes': [models.Index(fields=['operator', '-checked_in_at'], name='attendance__operato_a74e31_idx'), models.Index(fields=['checked_in_at'], name='attendance__checked_3d9e36_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('checked_out_at__isnull', True)), fields=('operator',), name='uniq_open_log_per_operator')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(default='10:00')),
                ('shift_end', models.TimeField(default='20:00')),
                ('late_threshold_min', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)])),
                ('auto_close_at', models.TimeField(default='23:00')),
                ('tg_checkin_enabled', models.BooleanField(default=True, help_text='Allows check-in/out via Telegram bot commands')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='attendance_settings_singleton')],
            },
        ),
        migrations.CreateModel(
            name='OperatorQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(help_text='16 hex bytes (32 characters). Enters HMAC signature.', max_length=32, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_qrs', to='operators.operator')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['nonce'], name='attendance__nonce_7ee225_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('operator',), name='uniq_active_qr_per_operator')],
            },
        ),
    ]
