# Generated by Django 5.2.15 on 2026-07-24 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='long_shift_warning_sent_at',
            field=models.DateTimeField(blank=True, help_text='Момент отправки предупреждения о длинной смене — защита от повторов', null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='manual_close_note',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='manually_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='manually_closed_by',
            field=models.ForeignKey(blank=True, help_text='Кто из TL/Manager закрыл смену руками', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='warning_dismissed_at',
            field=models.DateTimeField(blank=True, help_text="Оператор нажал 'Нет, продолжаю' — не шлём повтор", null=True),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='long_shift_warning_hours',
            field=models.PositiveSmallIntegerField(default=10, help_text='После скольких часов открытой смены слать warning'),
        ),
    ]
