# Generated by Django 5.2.15 on 2026-08-31 13:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_checkout_reminder_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='default_attendance_gate_pct',
            field=models.PositiveSmallIntegerField(default=85, help_text='Если посещаемость <N%% в месяце — оклад НЕ начисляется (только комиссия).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='default_grace_period_min',
            field=models.PositiveSmallIntegerField(default=20, help_text='Grace-минуты после `shift_start` — приход в этом окне НЕ считается опозданием (payroll).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='default_late_penalty_uzs',
            field=models.DecimalField(decimal_places=0, default=Decimal('50000'), help_text='Фиксированный штраф за каждое опоздание сверх grace (UZS).', max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='default_salary_uzs',
            field=models.DecimalField(decimal_places=0, default=Decimal('1500000'), help_text='Оклад по умолчанию (UZS). Если у оператора `salary_uzs` пусто — берётся отсюда.', max_digits=12),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='default_weekly_day_off',
            field=models.PositiveSmallIntegerField(default=6, help_text='Личный выходной по умолчанию (0=Пн … 6=Вс).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='default_weekly_free_absences',
            field=models.PositiveSmallIntegerField(default=1, help_text='Сколько пропусков в неделю «прощаются» без штрафа (сверх личного выходного).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
