# Generated by Django 5.2.15 on 2026-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubscription',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'Oʻzbekcha')], default='ru', max_length=4),
        ),
        migrations.AlterField(
            model_name='botsubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
