# Generated by Django 5.2.15 on 2026-07-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_botsubscription_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubscription',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
