# Generated by Django 5.2.15 on 2026-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_botsubscription_blocked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubscription',
            name='last_daily_report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
