# Generated by Django 5.2.15 on 2026-08-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_rename_bot_v2_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=280)),
                ('category', models.CharField(choices=[('morning', 'Утренняя'), ('evening', 'Вечерний'), ('weekly', 'Недельный'), ('owner', 'Владельцу'), ('operator', 'Операторам'), ('custom', 'Кастомный')], default='custom', max_length=32)),
                ('blocks', models.JSONField(default=list, help_text='List of block slugs referenced from report_blocks.BLOCKS.')),
                ('schedule_defaults', models.JSONField(blank=True, default=dict, help_text='Suggested defaults: {"schedule_time": "09:00:00", "schedule_days": ["mon","tue"], "period": "today", "language": "ru", "include_header": true}. Client copies these into the new-report form when the template is picked.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
