# Generated by Django 5.2.17 on 2026-09-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_birthday_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('sale_created', 'Новая продажа'), ('sale_returned', 'Возврат продажи'), ('sale_rejected', 'Продажа отклонена'), ('callback_overdue', 'Просроченный колбэк'), ('lead_assigned', 'Новый лид'), ('birthday', 'День рождения оператора'), ('sale_celebration', 'Овация за продажу коллеги'), ('system', 'Системное сообщение')], db_index=True, max_length=32),
        ),
    ]
