# Generated by Django 5.2.15 on 2026-06-13 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('team_lead', 'Тимлид'), ('manager', 'Менеджер'), ('operator', 'Оператор')], default='team_lead', max_length=16)),
                ('operator', models.ForeignKey(blank=True, help_text='Linked when this user logs in as a specific operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='operators.operator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
