# Generated by Django 5.2.15 on 2026-07-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text="Populated by the bot's /link_operator FSM once the user confirms their operator phone. Used to DM callback reminders.", null=True, unique=True),
        ),
    ]
