# Generated by Django 5.2.15 on 2026-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_deleted_at_operatorsecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorsecret',
            name='key_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which key from OPERATOR_PASSWORD_ENCRYPTION_KEYS was used to encrypt this row. Read alongside encrypted_password so we can rotate the master key without invalidating old rows.'),
        ),
    ]
