# Generated by Django 5.2.15 on 2026-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('team_lead', 'Тимлид'), ('manager', 'Менеджер'), ('operator', 'Оператор'), ('smm', 'SMM'), ('superadmin', 'Супер-админ')], default='team_lead', max_length=16),
        ),
    ]
