# Generated by Django 5.2.15 on 2026-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='provider_used',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
