# Generated by Django 5.2.15 on 2026-07-23 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('operators', '0002_operatormonthlyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone_code_hash', models.CharField(blank=True, default='', max_length=64)),
                ('encrypted_session', models.BinaryField(blank=True, default=b'')),
                ('tg_user_id', models.BigIntegerField(blank=True, null=True)),
                ('tg_username', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending_code', 'Ожидает код'), ('pending_2fa', 'Ожидает облачный пароль'), ('active', 'Активна'), ('expired', 'Истекла'), ('revoked', 'Отозвана'), ('error', 'Ошибка')], default='pending_code', max_length=16)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tg_session', to='operators.operator')),
            ],
            options={
                'verbose_name': 'TG-сессия',
                'verbose_name_plural': 'TG-сессии',
            },
        ),
        migrations.CreateModel(
            name='TgChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tg_chat_id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('private', 'Личный'), ('group', 'Группа'), ('channel', 'Канал')], max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('partner_name', models.CharField(blank=True, default='', max_length=200)),
                ('partner_phone', models.CharField(blank=True, default='', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_chats', to='leads.lead')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='tg_userclient.tgsession')),
            ],
            options={
                'verbose_name': 'TG-чат',
                'verbose_name_plural': 'TG-чаты',
                'unique_together': {('session', 'tg_chat_id')},
            },
        ),
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_message_id', models.BigIntegerField()),
                ('direction', models.CharField(choices=[('in', 'Входящее'), ('out', 'Исходящее')], max_length=3)),
                ('kind', models.CharField(choices=[('text', 'Текст'), ('voice', 'Голосовое'), ('photo', 'Фото'), ('video', 'Видео'), ('sticker', 'Стикер'), ('other', 'Другое')], max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('transcript_status', models.CharField(blank=True, default='', max_length=16)),
                ('voice_duration_sec', models.IntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tg_userclient.tgchat')),
            ],
            options={
                'verbose_name': 'TG-сообщение',
                'verbose_name_plural': 'TG-сообщения',
                'indexes': [models.Index(fields=['chat', 'sent_at'], name='tg_userclie_chat_id_ab21ff_idx')],
                'unique_together': {('chat', 'tg_message_id')},
            },
        ),
        migrations.CreateModel(
            name='TgAiInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('since', models.DateTimeField()),
                ('until', models.DateTimeField()),
                ('model_version', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=32)),
                ('summary', models.TextField()),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('red_flags', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='tg_userclient.tgchat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='tg_userclient.tgsession')),
            ],
            options={
                'verbose_name': 'TG AI-инсайт',
                'verbose_name_plural': 'TG AI-инсайты',
                'indexes': [models.Index(fields=['session', 'until'], name='tg_userclie_session_64067f_idx'), models.Index(fields=['chat', 'until'], name='tg_userclie_chat_id_57877a_idx')],
            },
        ),
    ]
