# Generated by Django 5.2.15 on 2026-07-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_userclient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgBackfillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('since', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'В работе'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=8)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chats_scanned', models.IntegerField(default=0)),
                ('messages_saved', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_jobs', to='tg_userclient.tgsession')),
            ],
            options={
                'verbose_name': 'TG Backfill Job',
                'verbose_name_plural': 'TG Backfill Jobs',
                'indexes': [models.Index(fields=['session', 'status'], name='tg_userclie_session_33674c_idx')],
            },
        ),
    ]
