# Generated by Django 5.2.15 on 2026-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_userclient', '0002_tgbackfilljob'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgsession',
            name='key_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which key from TG_SESSION_ENCRYPTION_KEYS was used to encrypt encrypted_session. Read alongside so we can rotate the master key without invalidating old rows.'),
        ),
    ]
