# Generated by Django 5.2.15 on 2026-07-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_userclient', '0003_tgsession_key_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgAiInsightAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error_retriable', 'Ошибка (повторить)'), ('error_permanent', 'Ошибка (неустранимая)')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attempts', to='tg_userclient.tgchat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attempts', to='tg_userclient.tgsession')),
            ],
            options={
                'verbose_name': 'TG AI Attempt',
                'verbose_name_plural': 'TG AI Attempts',
                'indexes': [models.Index(fields=['chat', 'attempted_at'], name='tg_userclie_chat_id_fe23a4_idx'), models.Index(fields=['status', 'next_retry_at'], name='tg_userclie_status_52ef57_idx')],
            },
        ),
    ]
