# Generated by Django 5.2.15 on 2026-06-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('global', 'Глобальное правило'), ('operator', 'Правило оператора')], default='global', max_length=16)),
                ('threshold', models.DecimalField(decimal_places=2, default=50000000, max_digits=14)),
                ('payout_type', models.CharField(choices=[('fixed', 'Фиксированный бонус'), ('percent', 'Процент от суммы сверх порога'), ('tiers', 'Прогрессивные тиры')], default='percent', max_length=16)),
                ('payout_value', models.DecimalField(decimal_places=2, default=3, max_digits=14)),
                ('tiers', models.JSONField(blank=True, default=list)),
                ('period', models.CharField(default='month', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rules', to='operators.operator')),
            ],
            options={
                'ordering': ['scope', 'operator_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope', 'operator')), fields=('operator',), name='uniq_active_operator_rule')],
            },
        ),
    ]
