# Generated by Django 5.2.15 on 2026-10-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0013_operator_managed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('kpi_snapshot', models.JSONField(default=dict)),
                ('synthesis_text', models.TextField(blank=True, default='')),
                ('top_priorities', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=64)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=64)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_tg_user_id', models.BigIntegerField(blank=True, null=True)),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ROPState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('last_briefing_at', models.DateTimeField(blank=True, null=True)),
                ('last_pulse_at', models.DateTimeField(blank=True, null=True)),
                ('last_evening_at', models.DateTimeField(blank=True, null=True)),
                ('last_weekly_at', models.DateTimeField(blank=True, null=True)),
                ('custom_prompt_additions', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ROP state',
                'verbose_name_plural': 'ROP state',
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=64)),
                ('priority', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('info', 'Info')], default='yellow', max_length=16)),
                ('dedup_key', models.CharField(db_index=True, max_length=160)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('message_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['alert_type', 'created_at'], name='rop_agent_a_alert_t_38222d_idx'), models.Index(fields=['dedup_key', 'created_at'], name='rop_agent_a_dedup_k_82cd9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorCoachingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('coaching_plan_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('skipped', 'skipped')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rop_coaching_logs', to='operators.operator')),
            ],
            options={
                'ordering': ('-date', 'operator_id'),
                'unique_together': {('operator', 'date')},
            },
        ),
    ]
