# Generated by Django 5.2.15 on 2026-06-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TacLookup',
            fields=[
                ('tac', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('device_type', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ['brand', 'model'],
                'indexes': [models.Index(fields=['brand', 'model'], name='catalog_tac_brand_f286c9_idx')],
            },
        ),
    ]
