# Generated by Django 5.2.15 on 2026-07-23 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0002_operatormonthlyplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorSheetAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_name', models.CharField(max_length=128, unique=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_aliases', to='operators.operator')),
            ],
            options={
                'ordering': ['alias_name'],
            },
        ),
        migrations.CreateModel(
            name='SheetSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('spreadsheet_id', models.CharField(max_length=128)),
                ('gid', models.BigIntegerField(help_text="Google Sheet's tab gid")),
                ('worksheet_name', models.CharField(blank=True, default='', help_text='Optional — if set, sync reads by name instead of gid.', max_length=128)),
                ('column_map', models.JSONField(blank=True, default=dict)),
                ('default_status', models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_progress', 'В работе'), ('callback_scheduled', 'Запланирован callback'), ('contacted_telegram', 'Написали в Telegram'), ('no_answer', 'Не берёт трубку'), ('won', 'Продажа'), ('lost', 'Потерян'), ('archived', 'Архив'), ('needs_review', 'Требует проверки')], default='new', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_row', models.PositiveIntegerField(default=0, help_text="1-based row index of the highest row we've imported so far. sync_sheets_leads only fetches rows above this and processes new ones. Set to 0 to force a full re-scan.")),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('spreadsheet_id', 'gid'), name='uniq_sheet_source_ss_gid')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=128)),
                ('phone_raw', models.CharField(blank=True, default='', help_text='Original phone value from the sheet, unnormalized.', max_length=64)),
                ('phone', models.CharField(blank=True, db_index=True, default='', help_text='Normalized to +998XXXXXXXXX. Empty if unparseable.', max_length=16)),
                ('phone_invalid', models.BooleanField(default=False, help_text='True if the raw phone could not be normalized to +998 + 9 digits.')),
                ('product_hint', models.CharField(blank=True, default='', help_text='What phone the customer said they want (from sheet).', max_length=256)),
                ('has_card', models.CharField(blank=True, default='', help_text="Free-text 'plastik kartangiz bormi?' answer.", max_length=64)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('in_progress', 'В работе'), ('callback_scheduled', 'Запланирован callback'), ('contacted_telegram', 'Написали в Telegram'), ('no_answer', 'Не берёт трубку'), ('won', 'Продажа'), ('lost', 'Потерян'), ('archived', 'Архив'), ('needs_review', 'Требует проверки')], db_index=True, default='new', max_length=32)),
                ('source', models.CharField(choices=[('sheet', 'Google Sheets'), ('manual', 'Ручной ввод'), ('bot', 'Telegram-бот')], default='sheet', max_length=16)),
                ('sheet_row_index', models.PositiveIntegerField(blank=True, help_text='1-based row index inside the source worksheet.', null=True)),
                ('needs_review', models.BooleanField(default=False, help_text="Sheet gave us an operator alias we don't know yet, or another signal the team lead should look at before assigning.")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra sheet columns (STATUS/IZOH/bitrix_deal_id/…) preserved verbatim.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, help_text='Currently-responsible operator (latest active LeadAssignment).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='operators.operator')),
                ('sheet_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.sheetsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('sheet_manual', 'Из таблицы (alias)'), ('auto_round_robin', 'Автоматически (RR)'), ('admin_reassign', 'Переназначение админом')], default='auto_round_robin', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='leads.lead')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignments', to='operators.operator')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='leads_leada_lead_id_bf526a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'operator'], name='leads_lead_status_21a162_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['needs_review'], name='leads_lead_needs_r_d8f9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_invalid'], name='leads_lead_phone_i_88b97b_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('sheet_source__isnull', False)), fields=('sheet_source', 'sheet_row_index'), name='uniq_lead_sheet_source_row'),
        ),
    ]
