# Generated by Django 5.2.15 on 2026-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsource',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
