# Generated by Django 5.2.16 on 2026-07-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_sheetsource_last_sync_error'),
        ('operators', '0003_operator_daily_lesson_opt_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='postpone_reason',
            field=models.CharField(blank=True, default='', help_text='Комментарий оператора: «после обеда», «ждёт зарплату», …', max_length=280),
        ),
        migrations.AddField(
            model_name='lead',
            name='postponed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Когда оператор нажал «Отложить на потом». NULL = активный.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='postponed_by',
            field=models.ForeignKey(blank=True, help_text='Кто отложил. При reassign обнуляется.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operators.operator'),
        ),
    ]
