# Generated by Django 5.2.15 on 2026-08-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_sms_jonatildi_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatuslabel',
            name='carry_over_next_day',
            field=models.BooleanField(db_index=True, default=False, help_text='Показывать этот статус первым в списке оператора на следующий день. Используется для «спец-лидов»: no_answer, phone_on, callback_scheduled и т.п. — их нужно добить, поэтому они всплывают наверх /my active раньше свежих.'),
        ),
        migrations.AlterField(
            model_name='leadassignment',
            name='source',
            field=models.CharField(choices=[('sheet_manual', 'Из таблицы (alias)'), ('auto_round_robin', 'Автоматически (RR)'), ('admin_reassign', 'Переназначение админом'), ('qimmatlik_retry', 'Retry после qimmatlik'), ('morning_split', 'Утренняя раздача'), ('auto_refill', 'Автопополнение пачки')], default='auto_round_robin', max_length=32),
        ),
    ]
