# Generated by Django 5.2.15 on 2026-08-22 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_leadassignment_operator_setnull'),
        ('operators', '0005_operator_blocking_gate_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'updated_at'], name='lead_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['operator', 'status'], name='lead_operator_status_idx'),
        ),
    ]
