# Generated by Django 5.2.15 on 2026-09-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_lead_lead_status_updated_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadassignment',
            name='source',
            field=models.CharField(choices=[('sheet_manual', 'Из таблицы (alias)'), ('auto_round_robin', 'Автоматически (RR)'), ('admin_reassign', 'Переназначение админом'), ('qimmatlik_retry', 'Retry после qimmatlik'), ('morning_split', 'Утренняя раздача'), ('auto_refill', 'Автопополнение пачки'), ('auto_rescue_touched', 'Rescue touched-лида с уволенного')], default='auto_round_robin', max_length=32),
        ),
    ]
