# Generated by Django 5.2.15 on 2026-09-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_alter_leadassignment_source'),
        ('operators', '0010_sip_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsource',
            name='allowed_operators',
            field=models.ManyToManyField(blank=True, help_text='Per-sheet operator pool. Empty = раздача всем активным (историческое поведение). Заполнено = только эти операторы получают лидов из этого шита (RR/refill/alias_or_rr пересекают глобальный пул с этим списком).', related_name='allowed_in_sheets', to='operators.operator'),
        ),
    ]
