# Generated by Django 5.2.18 on 2026-10-08 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0027_sheet_hot_fields_and_lead_hot_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="SheetWritebackJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("next_try_at", models.DateTimeField(db_index=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheet_writeback_jobs",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["done_at", "next_try_at"], name="sheet_wb_job_due_idx")
                ],
            },
        ),
    ]
