# Generated by Django 5.2.15 on 2026-07-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0002_operatormonthlyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_date', models.DateField(db_index=True)),
                ('language', models.CharField(default='ru', max_length=8)),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=128)),
                ('generated_by_model', models.CharField(default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['-quote_date'], name='greetings_d_quote_d_28f0fe_idx')],
                'unique_together': {('quote_date', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DailyGreetingShown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greeting_receipts', to='operators.operator')),
            ],
            options={
                'unique_together': {('operator', 'date')},
            },
        ),
    ]
