# Generated by Django 5.2.15 on 2026-07-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('lead_quality_by_source', models.JSONField(default=dict)),
                ('targeting_recommendations', models.JSONField(default=list)),
                ('top_products', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('model_version', models.CharField(default='', max_length=64)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['-period_start'], name='marketing_m_period__aafc67_idx')],
                'unique_together': {('period_start', 'period_end')},
            },
        ),
    ]
