# Generated by Django 5.2.15 on 2026-07-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('talked_interested', 'Разговор, интерес'), ('talked_callback', 'Просят перезвонить'), ('no_answer', 'Не берёт трубку'), ('wrong_number', 'Не тот номер'), ('rejected', 'Отказ'), ('tg_only', 'Написали в Telegram')], max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Выполнен'), ('overdue', 'Просрочен'), ('snoozed', 'Отложен'), ('superseded', 'Заменён')], db_index=True, default='pending', max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('dm_sent_at', models.DateTimeField(blank=True, help_text="Timestamp of the last Telegram DM notification. Used by `check_due_callbacks` to avoid spamming an operator's DM every cron tick after `remind_at` has passed.", null=True)),
            ],
            options={
                'ordering': ['remind_at'],
            },
        ),
    ]
