# Generated by Django 5.2.15 on 2026-07-23 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('leads', '0001_initial'),
        ('operators', '0002_operatormonthlyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='callattempt',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_attempts', to='operators.operator'),
        ),
        migrations.AddField(
            model_name='callbackreminder',
            name='call_attempt',
            field=models.ForeignKey(blank=True, help_text='If this reminder was created off a call outcome, points back to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='calls.callattempt'),
        ),
        migrations.AddField(
            model_name='callbackreminder',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_reminders', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='callbackreminder',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callback_reminders', to='operators.operator'),
        ),
        migrations.AddIndex(
            model_name='callattempt',
            index=models.Index(fields=['lead', '-created_at'], name='calls_calla_lead_id_6ba8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='callattempt',
            index=models.Index(fields=['operator', '-created_at'], name='calls_calla_operato_e84d97_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackreminder',
            index=models.Index(fields=['operator', 'status', 'remind_at'], name='calls_callb_operato_5f20d0_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackreminder',
            index=models.Index(fields=['status', 'remind_at'], name='calls_callb_status_6b3c8a_idx'),
        ),
    ]
