# Generated by Django 5.2.15 on 2026-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_operator_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='callattempt',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='recording_url_asterisk',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='recording_url_mobile',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='sip_call_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='source',
            field=models.CharField(blank=True, choices=[('click_to_call', 'Click-to-call'), ('sip_originated', 'SIP'), ('manual', 'Ручной'), ('android_log', 'Android log')], db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='callattempt',
            name='outcome',
            field=models.CharField(blank=True, choices=[('talked_interested', 'Разговор, интерес'), ('talked_callback', 'Просят перезвонить'), ('no_answer', 'Не берёт трубку'), ('wrong_number', 'Не тот номер'), ('rejected', 'Отказ'), ('tg_only', 'Написали в Telegram')], default='', max_length=32),
        ),
    ]
