# Generated by Django 5.2.15 on 2026-07-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0003_operator_daily_lesson_opt_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLessonAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_date', models.DateField()),
                ('status', models.CharField(choices=[('ok', 'ok'), ('skip', 'skip'), ('error', 'error')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=280)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Когда отправлен TG-DM для skipped/empty дней', null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_date', models.DateField(help_text='Дата, ЗА которую урок (вчера на момент генерации)')),
                ('summary', models.TextField(help_text='Абзац: как прошёл день')),
                ('highlights', models.JSONField(default=list, help_text='[{title, evidence}] — 2-3 сильные стороны')),
                ('tips', models.JSONField(default=list, help_text='[{title, why, example, action}] — 3 совета')),
                ('micro_lesson', models.CharField(help_text="Один узкий навык на сегодня: 'уточняй бюджет до презентации модели'", max_length=280)),
                ('stats_snapshot', models.JSONField(default=dict, help_text='{sales_count, revenue_uzs, avg_check, dialogs_count, avg_quality, callbacks_missed, leads_won, leads_lost, month_progress_pct}')),
                ('model_version', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Когда упало в TG-DM', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='Когда оператор открыл в UI', null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='operators.operator')),
            ],
            options={
                'indexes': [models.Index(fields=['operator', '-lesson_date'], name='lessons_dai_operato_1b54af_idx')],
                'constraints': [models.UniqueConstraint(fields=('operator', 'lesson_date'), name='unique_lesson_per_operator_per_day')],
            },
        ),
    ]
