# Generated by Django 5.2.15 on 2026-06-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('operators', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='operators.operator')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_lines', to='sales.sale')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['sale', 'operator'], name='sales_saleo_sale_id_d20738_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.channel')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_lines', to='sales.sale')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['sale', 'partner'], name='sales_salep_sale_id_fc1cce_idx')],
            },
        ),
    ]
