# Generated by Django 5.2.15 on 2026-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество единиц товара в этой продаже. По умолчанию 1 — поле не участвует в расчётах суммы (сумма считается уже с учётом штук), а служит для отчётности «сколько штук продано».'),
        ),
    ]
