# Generated by Django 5.2.15 on 2026-07-23 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('operators', '0002_operatormonthlyplan'),
        ('sales', '0007_nullable_operator_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='saleoperator',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='operators.operator'),
        ),
    ]
