# Generated by Django 5.2.15 on 2026-08-22 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_operator_blocking_gate_enabled'),
        ('sales', '0012_remove_sale_assigned_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'sold_at'], name='sale_status_sold_at_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_by', 'status'], name='sale_created_by_status_idx'),
        ),
    ]
