# Generated by Django 5.2.15 on 2026-07-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0002_operatormonthlyplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=8)),
                ('is_rare', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Who assigned the sticker (only meaningful for rare).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sticker', to='operators.operator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_rare', False)), fields=('emoji',), name='unique_common_sticker_emoji'), models.UniqueConstraint(condition=models.Q(('is_rare', True)), fields=('is_rare',), name='single_rare_sticker_holder')],
            },
        ),
    ]
